language: ruby
rvm:
  - 1.9.3
#  - 2.0.0
env:
  global:
    secure: "P3MuYQLKb8rVut+7M80hUT3rZnYSPSpXl2IDLx+1H5woCArmcLxXoDzFmdX3\n6rRMXJno9ujQ5DJJmwGmS5K/MCBwQC1n0AbKCYGQDhI33HlffoOYGfFqfzlO\nT8wNd/ZcMRDgK3a/KUQbUhWXUT7DQ+VjmcNLQkmpYvrJHa0E7Sg="
branches:
  only:
    - develop
script: rake travis
